### ISSUE TITLE
抽取文章类网页内容为空

### ISSUE THREAD

**Issue by yaoxiaona** [crawlab-team/crawlab-ai-sdk#1]
https://health.youth.cn/yw/202405/t20240521_15265279.htm

这个网址抽不到内容

![d5ae709520ba4aac75423cba1384740](https://github.com/crawlab-team/crawlab-ai-sdk/assets/38646906/cad98064-9f19-4b03-a78e-2a8a583fa4ae)

**Comment by tikazyq** [comment]
已解决

<img width="1369" alt="image" src="https://github.com/crawlab-team/crawlab-ai-sdk/assets/3393101/ca0c7859-4e60-4f9d-854d-2e724b69b92b">
